### ISSUE TITLE
Link provided redirects to Dashboard

### ISSUE THREAD

**Issue by KimGonzales** [learn-co-curriculum/js-dom-and-events-intro-to-the-dom-readme#2]
The link to view the page to code-along to, https://learn.co/tracks/javascript-with-style, redirects to personal dashboard.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @KimGonzales.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
